"""Target XML content for Mathcad Prime 3.1 settings files."""
from __future__ import annotations

APP_XML_31 = (
    '<?xml version="1.0" encoding="utf-8"?>'
    '<properties'
    ' xmlns:xsd="http://www.w3.org/2001/XMLSchema"'
    ' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
    ' xmlns="http://schemas.mathsoft.com/extended-properties">'
    '<appVersion release="F000">3.1.0.0</appVersion>'
    '<serializationVersion architecture="x64" Culture="en-US" UiCulture="en-US">3.1.0.0</serializationVersion>'
    '<engineVersion>3.0.0.266</engineVersion>'
    '<build>2015.02.25.001</build>'
    '<schemaPropertiesList>'
    '<schemaProperties name="App" version="1.3.4" />'
    '<schemaProperties name="Calculation" version="1.3.1" />'
    '<schemaProperties name="Integration" version="1.3.1" />'
    '<schemaProperties name="Math" version="5.3.2" />'
    '<schemaProperties name="Presentation" version="1.3.3" />'
    '<schemaProperties name="Provenance" version="1.3.1" />'
    '<schemaProperties name="Result" version="1.3.1" />'
    '<schemaProperties name="SimpleTypes" version="1.3.1" />'
    '<schemaProperties name="Units" version="12.3.1" />'
    '<schemaProperties name="Worksheet" version="5.3.10" />'
    '</schemaPropertiesList>'
    '</properties>'
)

CALC_XML_31 = (
    '﻿<?xml version="1.0" encoding="utf-8"?>'
    '<calculation cache-worksheet="true"'
    ' xmlns="http://schemas.ptc.com/mathcad/settings/calculation10">'
    '<builtInVariables array-origin="0" convergence-tolerance="0.001"'
    ' constraint-tolerance="0.001" prn-col-width="8" prn-precision="4" random-seed="1" />'
    '<calculationBehavior automatic-recalculation="true" strings-use-origin="false"'
    ' matrix-strict-singularity-check="false" exact-boolean="true"'
    ' units-in-symbolics="false" constants-in-symbolics="false" />'
    '<units><currentUnitSystem name="si" /></units>'
    '</calculation>'
)

PRES_XML_31 = (
    '﻿<?xml version="1.0" encoding="utf-8"?>'
    '<presentation xmlns:ws="http://schemas.mathsoft.com/worksheet50"'
    ' xmlns="http://schemas.ptc.com/mathcad/settings/presentation10">'
    '<pageModel paper-code="A4" grid-size="Fine" orientation="Portrait"'
    ' margin-type="Standard" show-grid="false" show-hf-grid="false"'
    ' plot-background-type="undefined" show-input-output-tag="true" />'
    '<mathRendering>'
    '<mathStyles>'
    '<mathStyle name="Variable" font-family="Mathcad UniMath Prime" font-size="14.666666666666668" font-weight="Normal" font-style="Italic" color="#FF000000" font-stretch="Normal" />'
    '<mathStyle name="Unit" font-family="Mathcad UniMath Prime" font-size="14.666666666666668" font-weight="Bold" font-style="Italic" color="#FF00008B" font-stretch="Normal" />'
    '<mathStyle name="Constant" font-family="Mathcad UniMath Prime" font-size="14.666666666666668" font-weight="Bold" font-style="Italic" color="#FF556B2F" font-stretch="Normal" />'
    '<mathStyle name="Function" font-family="Mathcad UniMath Prime" font-size="14.666666666666668" font-weight="Normal" font-style="Normal" color="#FF000000" font-stretch="Normal" />'
    '<mathStyle name="System" font-family="Mathcad UniMath Prime" font-size="14.666666666666668" font-weight="Bold" font-style="Normal" color="#FF000000" font-stretch="Normal" />'
    '<mathStyle name="Keyword" font-family="Mathcad UniMath Prime" font-size="14.666666666666668" font-weight="Bold" font-style="Normal" color="#FF000000" font-stretch="Normal" />'
    '</mathStyles>'
    '<formatting FontFamily="Mathcad UniMath Prime" FontSize="9" Bold="false" Italic="false" Underline="false" ForegroundColor="#FF000000" BackgroundColor="#00FFFFFF" />'
    '<ws:results>'
    '<decimal precision="1" show-trailing-zeros="false" radix="dec" imaginary-value="i" xmlns="http://schemas.mathsoft.com/worksheet50" />'
    '<matrix size="12,12" offset="0,0" show-indices="false" expand-nested-arrays="false" xmlns="http://schemas.mathsoft.com/worksheet50" />'
    '<ws:unit simplify-units="true" />'
    '</ws:results>'
    '</mathRendering>'
    '<textRendering>'
    '<textStyles>'
    '<textStyle name="areaLayoutStyle" font-family="Arial" font-size="9" font-weight="Normal" font-style="Normal" variants="Normal" background="#00FFFFFF" foreground="#FF000000" />'
    '<textStyle name="headerLayoutStyle" font-family="Tahoma" font-size="11" font-weight="Normal" font-style="Normal" variants="Normal" background="#00FFFFFF" foreground="#FF000000" />'
    '<textStyle name="footerLayoutStyle" font-family="Tahoma" font-size="11" font-weight="Normal" font-style="Normal" variants="Normal" background="#00FFFFFF" foreground="#FF000000" />'
    '</textStyles>'
    '</textRendering>'
    '</presentation>'
)
